// <auto-generated />
using System;
using HotJoes.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotJoes.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VendorRegistrationDbContext))]
    partial class VendorRegistrationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotJoes.Infrastructure.Persistence.VendorRegistrationOutboxRecord", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("ClaimExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claim_expires_at_utc");

                    b.Property<Guid?>("ClaimedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("claimed_by");

                    b.Property<int>("EventVersion")
                        .HasColumnType("integer")
                        .HasColumnName("event_version");

                    b.Property<bool>("IsStalled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_stalled");

                    b.Property<DateTimeOffset?>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at_utc");

                    b.Property<string>("LastFailureCategory")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_failure_category");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<byte[]>("SerializedEvent")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("serialized_event");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)")
                        .HasColumnName("trace_parent");

                    b.Property<string>("TraceState")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("trace_state");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.HasKey("EventId");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_vendor_registration_outbox_unpublished")
                        .HasFilter("published_at_utc IS NULL");

                    b.HasIndex("VendorId")
                        .IsUnique()
                        .HasDatabaseName("uq_vendor_registration_outbox_vendor_id");

                    b.HasIndex("NextAttemptAtUtc", "ClaimExpiresAtUtc", "EventId")
                        .HasDatabaseName("ix_vendor_registration_outbox_eligible")
                        .HasFilter("published_at_utc IS NULL AND is_stalled = FALSE");

                    b.ToTable("vendor_registration_outbox", null, t =>
                        {
                            t.HasCheckConstraint("ck_vendor_registration_outbox_attempt_count", "\"attempt_count\" >= 0");

                            t.HasCheckConstraint("ck_vendor_registration_outbox_claim", "(\"claimed_by\" IS NULL AND \"claim_expires_at_utc\" IS NULL) OR (\"claimed_by\" IS NOT NULL AND \"claim_expires_at_utc\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_vendor_registration_outbox_event_version", "\"event_version\" > 0");

                            t.HasCheckConstraint("ck_vendor_registration_outbox_serialized_event", "octet_length(\"serialized_event\") > 0");

                            t.HasCheckConstraint("ck_vendor_registration_outbox_stalled", "NOT \"is_stalled\" OR \"next_attempt_at_utc\" IS NULL");
                        });
                });

            modelBuilder.Entity("HotJoes.Infrastructure.Persistence.VendorRegistrationOutcomeRecord", b =>
                {
                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<short>("FingerprintVersion")
                        .HasColumnType("smallint")
                        .HasColumnName("fingerprint_version");

                    b.Property<string>("ResultVendorState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("result_vendor_state");

                    b.Property<byte[]>("SemanticFingerprintSha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("semantic_fingerprint_sha256");

                    b.HasKey("VendorId");

                    b.ToTable("vendor_registration_outcomes", null, t =>
                        {
                            t.HasCheckConstraint("ck_vendor_registration_outcomes_fingerprint_sha256", "octet_length(\"semantic_fingerprint_sha256\") = 32");

                            t.HasCheckConstraint("ck_vendor_registration_outcomes_fingerprint_version", "\"fingerprint_version\" > 0");

                            t.HasCheckConstraint("ck_vendor_registration_outcomes_result_vendor_state", "\"result_vendor_state\" = 'pendingActivation'");
                        });
                });

            modelBuilder.Entity("HotJoes.Infrastructure.Persistence.VendorRegistrationRecord", b =>
                {
                    b.Property<Guid>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address_line_1");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text")
                        .HasColumnName("address_line_2");

                    b.Property<string>("AddressLine3")
                        .HasColumnType("text")
                        .HasColumnName("address_line_3");

                    b.Property<bool>("AlcoholService")
                        .HasColumnType("boolean")
                        .HasColumnName("alcohol_service");

                    b.Property<string>("BusinessDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("business_description");

                    b.Property<string>("CanonicalAddressId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("canonical_address_id");

                    b.Property<string>("CompanyRegistrationNumber")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("company_registration_number");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contact_name");

                    b.Property<string>("ContactTelephone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_telephone");

                    b.Property<string>("County")
                        .HasColumnType("text")
                        .HasColumnName("county");

                    b.Property<string>("FoodRegistrationAuthority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("food_registration_authority");

                    b.Property<string>("LegalOperatorName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("legal_operator_name");

                    b.Property<string>("LegalOperatorType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("legal_operator_type");

                    b.Property<string>("NormalizedLegalOperatorName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("normalized_legal_operator_name");

                    b.Property<string>("NormalizedTradingName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("normalized_trading_name");

                    b.Property<TimeOnly>("OpeningHoursEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("opening_hours_end");

                    b.Property<TimeOnly>("OpeningHoursStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("opening_hours_start");

                    b.Property<string>("PostTown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("post_town");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("postcode");

                    b.Property<string>("PrimaryTradingAuthority")
                        .HasColumnType("text")
                        .HasColumnName("primary_trading_authority");

                    b.Property<string>("RecipientOrOrganisationName")
                        .HasColumnType("text")
                        .HasColumnName("recipient_or_organisation_name");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at_utc");

                    b.Property<bool>("ServiceIncludesHotFood")
                        .HasColumnType("boolean")
                        .HasColumnName("service_includes_hot_food");

                    b.Property<string>("TradingLocation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("trading_location");

                    b.Property<string>("TradingName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("trading_name");

                    b.Property<string>("TradingPreference")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("trading_preference");

                    b.Property<string>("VendorState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("vendor_state");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("VendorId");

                    b.HasIndex("NormalizedTradingName", "NormalizedLegalOperatorName", "CanonicalAddressId")
                        .IsUnique()
                        .HasDatabaseName("uq_vendor_registrations_identity");

                    b.ToTable("vendor_registrations", null, t =>
                        {
                            t.HasCheckConstraint("ck_vendor_registrations_company_registration_number", "((\"legal_operator_type\" IN ('limitedCompany', 'limitedLiabilityPartnership', 'charitableIncorporatedOrganisation') AND \"company_registration_number\" IS NOT NULL) OR (\"legal_operator_type\" NOT IN ('limitedCompany', 'limitedLiabilityPartnership', 'charitableIncorporatedOrganisation') AND \"company_registration_number\" IS NULL))");

                            t.HasCheckConstraint("ck_vendor_registrations_legal_operator_type", "\"legal_operator_type\" IN ('soleTrader', 'generalPartnership', 'limitedCompany', 'limitedLiabilityPartnership', 'charitableCommunityGroup', 'charitableIncorporatedOrganisation')");

                            t.HasCheckConstraint("ck_vendor_registrations_normalized_names", "length(\"normalized_trading_name\") > 0 AND \"normalized_trading_name\" = lower(btrim(\"normalized_trading_name\")) AND length(\"normalized_legal_operator_name\") > 0 AND \"normalized_legal_operator_name\" = lower(btrim(\"normalized_legal_operator_name\"))");

                            t.HasCheckConstraint("ck_vendor_registrations_primary_trading_authority", "((\"trading_location\" = 'stall' AND \"primary_trading_authority\" IS NOT NULL) OR (\"trading_location\" <> 'stall' AND \"primary_trading_authority\" IS NULL))");

                            t.HasCheckConstraint("ck_vendor_registrations_trading_location", "\"trading_location\" IN ('restaurant', 'stall', 'kitchen')");

                            t.HasCheckConstraint("ck_vendor_registrations_trading_preference", "\"trading_preference\" IN ('offline', 'online')");

                            t.HasCheckConstraint("ck_vendor_registrations_vendor_state", "\"vendor_state\" IN ('pendingActivation', 'activated', 'suspended', 'deactivated')");
                        });
                });

            modelBuilder.Entity("HotJoes.Infrastructure.Persistence.VendorRegistrationOutboxRecord", b =>
                {
                    b.HasOne("HotJoes.Infrastructure.Persistence.VendorRegistrationRecord", null)
                        .WithOne()
                        .HasForeignKey("HotJoes.Infrastructure.Persistence.VendorRegistrationOutboxRecord", "VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HotJoes.Infrastructure.Persistence.VendorRegistrationOutcomeRecord", b =>
                {
                    b.HasOne("HotJoes.Infrastructure.Persistence.VendorRegistrationRecord", null)
                        .WithOne()
                        .HasForeignKey("HotJoes.Infrastructure.Persistence.VendorRegistrationOutcomeRecord", "VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
