<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.4" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../HotJoes.Infrastructure.Persistence/HotJoes.Infrastructure.Persistence.csproj" />
  </ItemGroup>

</Project>
