// <auto-generated />
using System;
using HotJoes.Infrastructure.Community.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotJoes.Infrastructure.Community.Persistence.Migrations
{
    [DbContext(typeof(CommunityPersistenceDbContext))]
    partial class CommunityPersistenceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("community")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotJoes.Infrastructure.Community.Persistence.CommunityParticipationOutboxRecord", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("ClaimExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claim_expires_at_utc");

                    b.Property<Guid?>("ClaimedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("claimed_by");

                    b.Property<Guid>("CommunityParticipationId")
                        .HasColumnType("uuid")
                        .HasColumnName("community_participation_id");

                    b.Property<int>("EventVersion")
                        .HasColumnType("integer")
                        .HasColumnName("event_version");

                    b.Property<bool>("IsStalled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_stalled");

                    b.Property<DateTimeOffset?>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at_utc");

                    b.Property<string>("LastFailureCategory")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_failure_category");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<byte[]>("SerializedEvent")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("serialized_event");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)")
                        .HasColumnName("trace_parent");

                    b.Property<string>("TraceState")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("trace_state");

                    b.HasKey("EventId");

                    b.HasIndex("CommunityParticipationId")
                        .IsUnique()
                        .HasDatabaseName("uq_community_participation_outbox_participation_id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_community_participation_outbox_unpublished")
                        .HasFilter("published_at_utc IS NULL");

                    b.HasIndex("NextAttemptAtUtc", "ClaimExpiresAtUtc", "EventId")
                        .HasDatabaseName("ix_community_participation_outbox_eligible")
                        .HasFilter("published_at_utc IS NULL AND is_stalled = FALSE");

                    b.ToTable("community_participation_outbox", "community", t =>
                        {
                            t.HasCheckConstraint("ck_community_outbox_attempt_count", "\"attempt_count\" >= 0");

                            t.HasCheckConstraint("ck_community_outbox_claim", "(\"claimed_by\" IS NULL AND \"claim_expires_at_utc\" IS NULL) OR (\"claimed_by\" IS NOT NULL AND \"claim_expires_at_utc\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_community_outbox_event_version", "\"event_version\" > 0");

                            t.HasCheckConstraint("ck_community_outbox_serialized_event", "octet_length(\"serialized_event\") > 0");

                            t.HasCheckConstraint("ck_community_outbox_stalled", "NOT \"is_stalled\" OR \"next_attempt_at_utc\" IS NULL");
                        });
                });

            modelBuilder.Entity("HotJoes.Infrastructure.Community.Persistence.CommunityParticipationRecord", b =>
                {
                    b.Property<Guid>("CommunityParticipationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("community_participation_id");

                    b.Property<string>("ContactPreference")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("contact_preference");

                    b.Property<DateTimeOffset>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at_utc");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.HasKey("CommunityParticipationId");

                    b.HasIndex("VendorId")
                        .IsUnique()
                        .HasDatabaseName("uq_community_participations_vendor_id");

                    b.ToTable("community_participations", "community", t =>
                        {
                            t.HasCheckConstraint("ck_community_participations_contact_preference", "\"contact_preference\" IN ('email', 'sms', 'whatsApp')");
                        });
                });

            modelBuilder.Entity("HotJoes.Infrastructure.Community.Persistence.CommunityParticipationOutboxRecord", b =>
                {
                    b.HasOne("HotJoes.Infrastructure.Community.Persistence.CommunityParticipationRecord", null)
                        .WithOne()
                        .HasForeignKey("HotJoes.Infrastructure.Community.Persistence.CommunityParticipationOutboxRecord", "CommunityParticipationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
