// <auto-generated />
using System;
using HotJoes.Infrastructure.ComplianceConsumer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotJoes.Infrastructure.ComplianceConsumer.Migrations
{
    [DbContext(typeof(ComplianceReceiptDbContext))]
    [Migration("20260828000200_AddComplianceVendorRegisteredReceipts")]
    partial class AddComplianceVendorRegisteredReceipts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotJoes.Infrastructure.ComplianceConsumer.ComplianceReceiptRecord", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<int>("EventVersion")
                        .HasColumnType("integer")
                        .HasColumnName("event_version");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<byte[]>("SerializedEventSha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("serialized_event_sha256");

                    b.HasKey("EventId");

                    b.ToTable("compliance_vendor_registered_receipts", null, t =>
                        {
                            t.HasCheckConstraint("ck_compliance_receipts_event_type", "\"event_type\" = 'VendorRegistered'");

                            t.HasCheckConstraint("ck_compliance_receipts_event_version", "\"event_version\" = 1");

                            t.HasCheckConstraint("ck_compliance_receipts_sha256", "octet_length(\"serialized_event_sha256\") = 32");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
